import type { StaffingAssignment } from '../types/Project';
import { createWithFormData, updateWithFormData, remove } from './apiUtils';

// Commitment segment type
export interface CommitmentSegment {
  start_date: string;
  end_date: string;
  commitment: number;
}

// Define the payload structure for creating/updating assignments
// Excludes fields generated by backend (ID) or nested objects (Employee)
// Includes project_id for creation
export type AssignmentPayload = {
  project_id?: number; // Required for creation
  employee_id: number;
  commitment?: number | undefined; // Legacy/average for backward compatibility
  start_date: string;
  end_date: string;
  segments?: CommitmentSegment[]; // New flexible scheduling
};

// Type for data structure passed *to* these functions (now uses employee_id)
export type AssignmentInputData = {
  project_id?: number; // Required for creation only
  employee_id: number; // Changed from staff_id
  commitment?: number | undefined;
  start_date: string;
  end_date: string;
  segments?: CommitmentSegment[];
};

// Type for the actual payload sent *to the API* (already uses employee_id)
type ApiAssignmentPayload = {
  project_id?: number;
  employee_id: number; 
  commitment?: number | undefined;
  start_date: string;
  end_date: string;
  segments?: CommitmentSegment[];
};

/**
 * Creates a new staffing assignment for a project.
 * @param projectId The ID of the project.
 * @param assignmentData Data for the new assignment (using employee_id).
 * @returns Promise with the created assignment.
 */
export const createProjectAssignment = async (
  projectId: number,
  assignmentData: Omit<AssignmentInputData, 'project_id'>
): Promise<StaffingAssignment> => {
  // Construct payload, mapping is no longer needed
  const payload: ApiAssignmentPayload = {
    ...assignmentData, // contains employee_id directly now
    project_id: projectId,
  };

  try {
    return await createWithFormData<StaffingAssignment>('project_assignments', payload);
  } catch (error) {
      console.error('API Error Creating Project Assignment:', error);
      throw error;
  }
};

/**
 * Updates an existing staffing assignment.
 * @param assignmentId The ID of the assignment to update.
 * @param assignmentData The partial data to update (using employee_id).
 * @returns Promise with the updated assignment.
 */
export const updateProjectAssignment = async (
  assignmentId: number,
  assignmentData: Partial<Omit<AssignmentInputData, 'project_id'>>
): Promise<StaffingAssignment> => {
  // Payload uses employee_id directly, no mapping needed
  const payload: Partial<ApiAssignmentPayload> = assignmentData;

  try {
    return await updateWithFormData<StaffingAssignment>(
      'project_assignments',
      assignmentId,
      payload
    );
  } catch (error) {
      console.error(`API Error Updating Project Assignment ${assignmentId}:`, error);
      throw error;
  }
};

/**
 * Deletes a staffing assignment.
 * @param assignmentId The ID of the assignment to delete.
 * @returns Promise<void>
 */
export const deleteProjectAssignment = async (
  assignmentId: number
): Promise<void> => {
  try {
    await remove('project_assignments', assignmentId);
  } catch (error) {
      console.error(`API Error Deleting Project Assignment ${assignmentId}:`, error);
      throw error;
  }
};

// Optional: Add a function to get assignments for a project if needed directly
// export const getProjectAssignments = async (projectId: number): Promise<StaffingAssignment[]> => { ... } 